system:
  ip:
  port: 8080
  env: dev
log:
  app: blogX_server
  dir: logs
dbr:
  user: root
  password: r
  host: 127.0.0.1
  port: 3306
  db: blog_x
  debug: false
  source: mysql
dbw:
  user: root
  password: r
  host: 127.0.0.1
  port: 3306
  db: blog_x
  debug: false
  source: mysql